#!/bin/bash

STRAL() {
chown root:root /
chmod 755 /
clear
/bin/echo -e '\n\n' "\e[1;36mRUNNING IN CHROOT ENVIRONMENT...

\e[0m"

read -p "Enter Hostname : " HOSTNAME 
echo "

"
read -p "Enter Username: " USERNAME
echo "

"
clear
/bin/echo -e '\n\n' "\e[1;32mRE-ENTER THE FOLLOWING PARTITIONS FOR CHROOT ENVIRONMENT!...

\e[0m"
lsblk
echo "

"
read -p "RE-Enter EFI partition for creating fstab  (eg: sda1,vda1,nvme01) : " GEN_EFI
echo "

"
read -p "RE-Enter the Encrypted partition (eg: sda2,vda2,nvme02) : " ECRVLM
}

AUTOCON(){
model=$(lscpu | grep 'Model name')
case "$model" in
    *Intel*) xbps-install -Syu void-repo-nonfree && xbps-install -Syu intel-ucode ;;
    *AMD*) xbps-install -Syu linux-firmware-amd ;;  
esac

chsh -s /bin/zsh
/bin/echo -e '\n\n' "\e[1;33mEnter root password

\e[0m"
passwd root

useradd --create-home --groups wheel,users,audio,video,storage,cdrom,input,network --shell /bin/zsh $USERNAME
/bin/echo -e '\n\n' "\e[1;33mEnter user password

\e[0m"
passwd $USERNAME

echo "root ALL=(ALL) ALL 
%wheel ALL=(ALL) ALL 
%wheel ALL=(ALL) NOPASSWD: /usr/bin/halt, /usr/bin/poweroff, /usr/bin/reboot, \
	/usr/bin/shutdown, /usr/bin/zzz, /usr/bin/ZZZ
@includedir /etc/sudoers.d" > /etc/sudoers


echo $HOSTNAME > /etc/hostname
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "en_US.UTF-8 UTF-8" >> /etc/default/libc-locales
xbps-reconfigure -f glibc-locales


UUID_EFI=$(blkid -o value -s UUID /dev/$GEN_EFI)
UUID_ROOT=$(blkid -o value -s UUID /dev/$ECRVLM)
UUID_LVMROOT=$(blkid -o value -s UUID /dev/voidvm/root)
UUID_LVMSWAP=$(blkid -o value -s UUID /dev/voidvm/swap) 

echo "UUID=${UUID_EFI}	/boot/efi	vfat	defaults	  0       0" > /etc/fstab	      
echo "UUID=${UUID_LVMROOT}  /     ext4     defaults             0       0" >> /etc/fstab
echo "UUID=${UUID_LVMSWAP}  swap  swap    defaults              0       0" >> /etc/fstab
}

GRB_BG(){
echo "GRUB_ENABLE_CRYPTODISK=y" >> /etc/default/grub 
sed -i 's|GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4"|GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4 rd.lvm.vg=voidvm rd.luks.uuid='$UUID_ROOT'"|g' /etc/default/grub


dd bs=1 count=64 if=/dev/urandom of=/boot/volume.key
cryptsetup luksAddKey /dev/$ECRVLM /boot/volume.key
chmod 000 /boot/volume.key
chmod -R g-rwx,o-rwx /boot
echo "voidvm  UUID=${UUID_ROOT}  /boot/volume.key   luks" >> /etc/crypttab
touch /etc/dracut.conf.d/10-crypt.conf
echo 'install_items+=" /boot/volume.key /etc/crypttab "' >> /etc/dracut.conf.d/10-crypt.conf


grub-install --target=x86_64-efi --efi-directory=/boot/efi
grub-mkconfig -o /boot/grub/grub.cfg
xbps-reconfigure -fa
ln -s /etc/sv/dhcpcd /etc/runit/runsvdir/default/
echo 'FONT="ter-g18b"' >> /etc/rc.conf
echo 'FONT_MAP="8859-2"' >> /etc/rc.conf
exit
}


#begin func
STRAL
AUTOCON
GRB_BG
















